import type {
  Developer,
  DistrictInfo,
  NearbyAmenity,
  PriceIndex,
  Project,
  PsfDataPoint,
  Transaction,
  UnitMixRow,
} from "./types";

// ─── Developers ───────────────────────────────────────────────

export const developers: Developer[] = [
  {
    id: "dev-1",
    name: "City Developments Limited",
    slug: "city-developments-limited",
    description:
      "One of Singapore's largest property groups by market capitalisation. CDL has developed over 50,000 homes across the island and maintains a diversified global portfolio.",
    website: "https://www.cdl.com.sg",
    logoUrl: null,
    projectCount: 3,
    totalUnits: 2105,
  },
  {
    id: "dev-2",
    name: "CapitaLand Development",
    slug: "capitaland-development",
    description:
      "The development arm of CapitaLand Group, one of Asia's largest diversified real estate groups. Active across residential, commercial, and integrated developments.",
    website: "https://www.capitaland.com",
    logoUrl: null,
    projectCount: 2,
    totalUnits: 1283,
  },
  {
    id: "dev-3",
    name: "Sim Lian Group",
    slug: "sim-lian-group",
    description:
      "A home-grown Singapore developer known for value-for-money projects in the OCR. Sim Lian has been in the industry since 1976 and has completed over 20 residential projects.",
    website: "https://www.simlian.com.sg",
    logoUrl: null,
    projectCount: 1,
    totalUnits: 620,
  },
];

// ─── Projects ─────────────────────────────────────────────────

export const projects: Project[] = [
  {
    id: "proj-1",
    name: "Aurelle of Tampines",
    slug: "aurelle-of-tampines",
    developerId: "dev-1",
    developerName: "City Developments Limited",
    districtNumber: 18,
    region: "OCR",
    address: "Tampines Street 62",
    postalCode: "528888",
    tenure: "99-year",
    tenureYears: 99,
    totalUnits: 760,
    unitsSold: 668,
    launchDate: "2025-03-15",
    topDate: "2029",
    completionDate: "2029-06-30",
    status: "selling",
    latitude: 1.3496,
    longitude: 103.9568,
    siteArea: 22014,
    plotRatio: 2.8,
    description:
      "Aurelle of Tampines is a 760-unit executive condominium nestled in the heart of Tampines, one of Singapore's most established residential towns. The development offers a comprehensive suite of facilities including a 50-metre lap pool, gymnasium, and lush landscaped gardens.",
    aiSummary:
      "Strong value proposition for upgraders at $1,488–$1,680 psf. The Tampines location benefits from Cross Island Line construction, which could drive future appreciation. Current take-up rate of 88% indicates robust demand. Comparable ECs in the area have seen 30–45% appreciation over 5 years post-TOP. Key risk: potential oversupply in Tampines North with multiple upcoming launches.",
  },
  {
    id: "proj-2",
    name: "Arina East Residences",
    slug: "arina-east-residences",
    developerId: "dev-2",
    developerName: "CapitaLand Development",
    districtNumber: 15,
    region: "RCR",
    address: "Tanjong Rhu Road",
    postalCode: "436886",
    tenure: "99-year",
    tenureYears: 99,
    totalUnits: 346,
    unitsSold: 242,
    launchDate: "2025-06-01",
    topDate: "2029",
    completionDate: "2029-12-31",
    status: "selling",
    latitude: 1.2978,
    longitude: 103.8735,
    siteArea: 12800,
    plotRatio: 2.1,
    description:
      "Arina East Residences is a boutique development along Tanjong Rhu Road, offering panoramic views of the Kallang Basin and Marina Bay skyline. The project features a curated collection of 1- to 4-bedroom units designed for modern urban living.",
    aiSummary:
      "Premium RCR positioning at $2,320–$2,680 psf, justified by waterfront views and proximity to the future Tanjong Rhu MRT station on the Thomson–East Coast Line. The Marine Parade enclave continues to gentrify. Comparable RCR launches in D15 have achieved $2,400+ psf. Smaller unit count (346) supports price resilience. Risk: high entry price may limit resale liquidity.",
  },
  {
    id: "proj-3",
    name: "One Marina Gardens",
    slug: "one-marina-gardens",
    developerId: "dev-2",
    developerName: "CapitaLand Development",
    districtNumber: 1,
    region: "CCR",
    address: "Marina Gardens Drive",
    postalCode: "018983",
    tenure: "99-year",
    tenureYears: 99,
    totalUnits: 937,
    unitsSold: 580,
    launchDate: "2025-09-01",
    topDate: "2030",
    completionDate: "2030-06-30",
    status: "selling",
    latitude: 1.2789,
    longitude: 103.8575,
    siteArea: 18600,
    plotRatio: 3.0,
    description:
      "One Marina Gardens is a landmark integrated development in the Marina Bay precinct, comprising two 34-storey residential towers atop a retail podium. Residents will enjoy unrivalled views of Gardens by the Bay and the Marina Bay skyline.",
    aiSummary:
      "Trophy asset in Singapore's premier address. At $2,700–$3,200 psf, pricing is competitive versus Meyer Mansion ($2,800) and Canninghill Piers ($3,100). The Gardens by the Bay neighbourhood is maturing rapidly. 62% take-up suggests healthy absorption. Potential upside from NS–EW interchange at Marina Bay. Risk: large quantum (most units above $2M) limits buyer pool.",
  },
  {
    id: "proj-4",
    name: "Norwood Grand",
    slug: "norwood-grand",
    developerId: "dev-1",
    developerName: "City Developments Limited",
    districtNumber: 23,
    region: "OCR",
    address: "Woodlands Avenue 1",
    postalCode: "739001",
    tenure: "99-year",
    tenureYears: 99,
    totalUnits: 348,
    unitsSold: 114,
    launchDate: "2025-11-01",
    topDate: "2029",
    completionDate: "2029-09-30",
    status: "launched",
    latitude: 1.4382,
    longitude: 103.7865,
    siteArea: 10200,
    plotRatio: 2.5,
    description:
      "Norwood Grand is a mid-scale condominium in the Woodlands Regional Centre, designed for families and young professionals. The development is directly connected to Woodlands South MRT station via a covered walkway.",
    aiSummary:
      "Affordable entry at $1,380–$1,520 psf in a transforming neighbourhood. Woodlands Regional Centre masterplan and RTS Link to Johor Bahru (2026) provide structural catalysts. Current take-up of 33% is cautious — typical for OCR launches in the north. Upside if Woodlands transformation delivers on promise. Risk: competing supply from adjacent Woodlands and Sembawang launches.",
  },
  {
    id: "proj-5",
    name: "The Collective at One Sophia",
    slug: "the-collective-at-one-sophia",
    developerId: "dev-1",
    developerName: "City Developments Limited",
    districtNumber: 9,
    region: "CCR",
    address: "Sophia Road",
    postalCode: "228149",
    tenure: "freehold",
    tenureYears: null,
    totalUnits: 997,
    unitsSold: 0,
    launchDate: "2026-06-01",
    topDate: "2030",
    completionDate: null,
    status: "upcoming",
    latitude: 1.3018,
    longitude: 103.8482,
    siteArea: 15500,
    plotRatio: 3.5,
    description:
      "The Collective at One Sophia is an upcoming freehold mixed-use development in the Dhoby Ghaut precinct. Set to be one of the largest freehold launches in the CCR, the project combines residential units with retail and co-working spaces.",
    aiSummary: null,
  },
  {
    id: "proj-6",
    name: "Tampines GreenVista",
    slug: "tampines-greenvista",
    developerId: "dev-3",
    developerName: "Sim Lian Group",
    districtNumber: 18,
    region: "OCR",
    address: "Tampines Avenue 11",
    postalCode: "529694",
    tenure: "99-year",
    tenureYears: 99,
    totalUnits: 620,
    unitsSold: 620,
    launchDate: "2022-06-15",
    topDate: "2026",
    completionDate: "2026-03-31",
    status: "completed",
    latitude: 1.3521,
    longitude: 103.9498,
    siteArea: 19800,
    plotRatio: 2.5,
    description:
      "Tampines GreenVista is a fully sold-out executive condominium that achieved TOP in early 2026. The development features extensive greenery, a rooftop garden, and proximity to Tampines Hub and Our Tampines Hub.",
    aiSummary:
      "A benchmark for the Tampines EC submarket. Launched at $1,100–$1,280 psf in 2022 and now transacting at $1,400–$1,550 psf on the resale market — a 27–35% gain in under 4 years. Owners who entered early have achieved strong capital appreciation. The project validates demand for well-located ECs in mature estates.",
  },
];

// ─── Unit Mix per Project ────────────────────────────────────

export const unitMixByProject: Record<string, UnitMixRow[]> = {
  "aurelle-of-tampines": [
    {
      unitType: "2BR",
      sizeSqftMin: 570,
      sizeSqftMax: 635,
      pricePsf: 1520,
      priceFrom: 866400,
      priceTo: 965200,
      totalCount: 152,
      soldCount: 140,
    },
    {
      unitType: "3BR",
      sizeSqftMin: 840,
      sizeSqftMax: 915,
      pricePsf: 1488,
      priceFrom: 1249920,
      priceTo: 1361520,
      totalCount: 304,
      soldCount: 275,
    },
    {
      unitType: "4BR",
      sizeSqftMin: 1076,
      sizeSqftMax: 1184,
      pricePsf: 1540,
      priceFrom: 1657040,
      priceTo: 1823360,
      totalCount: 228,
      soldCount: 194,
    },
    {
      unitType: "5BR",
      sizeSqftMin: 1356,
      sizeSqftMax: 1432,
      pricePsf: 1620,
      priceFrom: 2196720,
      priceTo: 2319840,
      totalCount: 76,
      soldCount: 59,
    },
  ],
  "arina-east-residences": [
    {
      unitType: "1BR",
      sizeSqftMin: 452,
      sizeSqftMax: 506,
      pricePsf: 2580,
      priceFrom: 1166160,
      priceTo: 1305480,
      totalCount: 52,
      soldCount: 41,
    },
    {
      unitType: "2BR",
      sizeSqftMin: 646,
      sizeSqftMax: 721,
      pricePsf: 2450,
      priceFrom: 1582700,
      priceTo: 1766450,
      totalCount: 104,
      soldCount: 78,
    },
    {
      unitType: "3BR",
      sizeSqftMin: 936,
      sizeSqftMax: 1012,
      pricePsf: 2380,
      priceFrom: 2227680,
      priceTo: 2408560,
      totalCount: 121,
      soldCount: 82,
    },
    {
      unitType: "4BR",
      sizeSqftMin: 1238,
      sizeSqftMax: 1356,
      pricePsf: 2320,
      priceFrom: 2872160,
      priceTo: 3145920,
      totalCount: 52,
      soldCount: 31,
    },
    {
      unitType: "Penthouse",
      sizeSqftMin: 1872,
      sizeSqftMax: 2145,
      pricePsf: 2680,
      priceFrom: 5016960,
      priceTo: 5748600,
      totalCount: 17,
      soldCount: 10,
    },
  ],
  "one-marina-gardens": [
    {
      unitType: "1BR",
      sizeSqftMin: 484,
      sizeSqftMax: 538,
      pricePsf: 2980,
      priceFrom: 1442320,
      priceTo: 1603240,
      totalCount: 140,
      soldCount: 95,
    },
    {
      unitType: "2BR",
      sizeSqftMin: 678,
      sizeSqftMax: 764,
      pricePsf: 2850,
      priceFrom: 1932300,
      priceTo: 2177400,
      totalCount: 281,
      soldCount: 180,
    },
    {
      unitType: "3BR",
      sizeSqftMin: 1024,
      sizeSqftMax: 1128,
      pricePsf: 2780,
      priceFrom: 2846720,
      priceTo: 3135840,
      totalCount: 328,
      soldCount: 198,
    },
    {
      unitType: "4BR",
      sizeSqftMin: 1356,
      sizeSqftMax: 1512,
      pricePsf: 2700,
      priceFrom: 3661200,
      priceTo: 4082400,
      totalCount: 140,
      soldCount: 82,
    },
    {
      unitType: "Penthouse",
      sizeSqftMin: 2340,
      sizeSqftMax: 3120,
      pricePsf: 3200,
      priceFrom: 7488000,
      priceTo: 9984000,
      totalCount: 48,
      soldCount: 25,
    },
  ],
  "norwood-grand": [
    {
      unitType: "1BR",
      sizeSqftMin: 431,
      sizeSqftMax: 474,
      pricePsf: 1480,
      priceFrom: 637880,
      priceTo: 701520,
      totalCount: 70,
      soldCount: 28,
    },
    {
      unitType: "2BR",
      sizeSqftMin: 592,
      sizeSqftMax: 657,
      pricePsf: 1420,
      priceFrom: 840640,
      priceTo: 932940,
      totalCount: 105,
      soldCount: 38,
    },
    {
      unitType: "3BR",
      sizeSqftMin: 872,
      sizeSqftMax: 947,
      pricePsf: 1380,
      priceFrom: 1203360,
      priceTo: 1306860,
      totalCount: 105,
      soldCount: 32,
    },
    {
      unitType: "4BR",
      sizeSqftMin: 1108,
      sizeSqftMax: 1205,
      pricePsf: 1520,
      priceFrom: 1684160,
      priceTo: 1831600,
      totalCount: 68,
      soldCount: 16,
    },
  ],
  "the-collective-at-one-sophia": [
    {
      unitType: "1BR",
      sizeSqftMin: 420,
      sizeSqftMax: 495,
      pricePsf: 2800,
      priceFrom: 1176000,
      priceTo: 1386000,
      totalCount: 199,
      soldCount: 0,
    },
    {
      unitType: "2BR",
      sizeSqftMin: 624,
      sizeSqftMax: 732,
      pricePsf: 2650,
      priceFrom: 1653600,
      priceTo: 1939800,
      totalCount: 299,
      soldCount: 0,
    },
    {
      unitType: "3BR",
      sizeSqftMin: 958,
      sizeSqftMax: 1082,
      pricePsf: 2550,
      priceFrom: 2442900,
      priceTo: 2759100,
      totalCount: 299,
      soldCount: 0,
    },
    {
      unitType: "4BR",
      sizeSqftMin: 1285,
      sizeSqftMax: 1420,
      pricePsf: 2480,
      priceFrom: 3186800,
      priceTo: 3521600,
      totalCount: 150,
      soldCount: 0,
    },
    {
      unitType: "Penthouse",
      sizeSqftMin: 2100,
      sizeSqftMax: 2850,
      pricePsf: 2950,
      priceFrom: 6195000,
      priceTo: 8407500,
      totalCount: 50,
      soldCount: 0,
    },
  ],
  "tampines-greenvista": [
    {
      unitType: "2BR",
      sizeSqftMin: 560,
      sizeSqftMax: 624,
      pricePsf: 1180,
      priceFrom: 660800,
      priceTo: 736320,
      totalCount: 124,
      soldCount: 124,
    },
    {
      unitType: "3BR",
      sizeSqftMin: 828,
      sizeSqftMax: 904,
      pricePsf: 1140,
      priceFrom: 943920,
      priceTo: 1030560,
      totalCount: 248,
      soldCount: 248,
    },
    {
      unitType: "4BR",
      sizeSqftMin: 1056,
      sizeSqftMax: 1152,
      pricePsf: 1200,
      priceFrom: 1267200,
      priceTo: 1382400,
      totalCount: 186,
      soldCount: 186,
    },
    {
      unitType: "5BR",
      sizeSqftMin: 1320,
      sizeSqftMax: 1408,
      pricePsf: 1280,
      priceFrom: 1689600,
      priceTo: 1802240,
      totalCount: 62,
      soldCount: 62,
    },
  ],
};

// ─── PSF Trends per Project ──────────────────────────────────

function generatePsfTrend(basePsf: number, months: number): PsfDataPoint[] {
  const points: PsfDataPoint[] = [];
  const monthNames = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];

  for (let i = 0; i < months; i++) {
    const monthIndex = (3 + i) % 12;
    const year = 2025 + Math.floor((3 + i) / 12);
    const variation = Math.sin(i * 0.8) * 40 + i * 8;
    points.push({
      month: `${monthNames[monthIndex]} ${year.toString().slice(-2)}`,
      psf: Math.round(basePsf + variation),
    });
  }
  return points;
}

export const psfTrendByProject: Record<string, PsfDataPoint[]> = {
  "aurelle-of-tampines": generatePsfTrend(1488, 12),
  "arina-east-residences": generatePsfTrend(2320, 12),
  "one-marina-gardens": generatePsfTrend(2700, 12),
  "norwood-grand": generatePsfTrend(1380, 12),
  "the-collective-at-one-sophia": generatePsfTrend(2650, 12),
  "tampines-greenvista": generatePsfTrend(1100, 12),
};

// ─── Transactions ────────────────────────────────────────────

function generateTransactions(
  slug: string,
  name: string,
  district: number,
  basePsf: number,
  tenure: string,
  count: number,
): Transaction[] {
  const floors = ["01-05", "06-10", "11-15", "16-20", "21-25", "26-30"];
  const txns: Transaction[] = [];

  for (let i = 0; i < count; i++) {
    const floor = floors[i % floors.length];
    const unit = `#${String(Math.floor(i / 6) + 1).padStart(2, "0")}-${String((i % 8) + 1).padStart(2, "0")}`;
    const areaSqft = 500 + Math.floor(Math.random() * 800);
    const psfVariation = basePsf + Math.floor(Math.random() * 200) - 100;
    const month = String((i % 12) + 1).padStart(2, "0");
    const day = String((i % 28) + 1).padStart(2, "0");

    txns.push({
      id: `txn-${slug}-${i}`,
      projectSlug: slug,
      projectName: name,
      unitNumber: unit,
      floorRange: floor,
      areaSqft,
      transactedPrice: areaSqft * psfVariation,
      pricePsf: psfVariation,
      contractDate: `2025-${month}-${day}`,
      saleType: "new_sale",
      propertyType: "condo",
      district,
      tenure,
    });
  }
  return txns;
}

export const transactionsByProject: Record<string, Transaction[]> = {
  "aurelle-of-tampines": generateTransactions(
    "aurelle-of-tampines",
    "Aurelle of Tampines",
    18,
    1520,
    "99-year",
    18,
  ),
  "arina-east-residences": generateTransactions(
    "arina-east-residences",
    "Arina East Residences",
    15,
    2450,
    "99-year",
    15,
  ),
  "one-marina-gardens": generateTransactions(
    "one-marina-gardens",
    "One Marina Gardens",
    1,
    2850,
    "99-year",
    20,
  ),
  "norwood-grand": generateTransactions(
    "norwood-grand",
    "Norwood Grand",
    23,
    1420,
    "99-year",
    12,
  ),
  "the-collective-at-one-sophia": generateTransactions(
    "the-collective-at-one-sophia",
    "The Collective at One Sophia",
    9,
    2650,
    "Freehold",
    0,
  ),
  "tampines-greenvista": generateTransactions(
    "tampines-greenvista",
    "Tampines GreenVista",
    18,
    1180,
    "99-year",
    16,
  ),
};

// ─── Nearby Amenities per Project ────────────────────────────

export const amenitiesByProject: Record<string, NearbyAmenity[]> = {
  "aurelle-of-tampines": [
    {
      id: "a-1",
      amenityType: "mrt",
      name: "Tampines MRT (EW2/DT32)",
      distanceMeters: 450,
      walkMinutes: 6,
    },
    {
      id: "a-2",
      amenityType: "mrt",
      name: "Tampines East MRT (DT33)",
      distanceMeters: 620,
      walkMinutes: 8,
    },
    {
      id: "a-3",
      amenityType: "mall",
      name: "Tampines Mall",
      distanceMeters: 500,
      walkMinutes: 7,
    },
    {
      id: "a-4",
      amenityType: "mall",
      name: "Tampines 1",
      distanceMeters: 550,
      walkMinutes: 7,
    },
    {
      id: "a-5",
      amenityType: "school",
      name: "St Hilda's Primary School",
      distanceMeters: 380,
      walkMinutes: 5,
    },
    {
      id: "a-6",
      amenityType: "school",
      name: "Poi Ching School",
      distanceMeters: 650,
      walkMinutes: 8,
    },
    {
      id: "a-7",
      amenityType: "park",
      name: "Tampines Eco Green",
      distanceMeters: 300,
      walkMinutes: 4,
    },
    {
      id: "a-8",
      amenityType: "hospital",
      name: "Tampines Polyclinic",
      distanceMeters: 800,
      walkMinutes: 10,
    },
  ],
  "arina-east-residences": [
    {
      id: "a-9",
      amenityType: "mrt",
      name: "Tanjong Rhu MRT (TE25)",
      distanceMeters: 200,
      walkMinutes: 3,
    },
    {
      id: "a-10",
      amenityType: "mrt",
      name: "Stadium MRT (CC6)",
      distanceMeters: 650,
      walkMinutes: 8,
    },
    {
      id: "a-11",
      amenityType: "mall",
      name: "Katong V",
      distanceMeters: 700,
      walkMinutes: 9,
    },
    {
      id: "a-12",
      amenityType: "school",
      name: "Tanjong Katong Primary School",
      distanceMeters: 500,
      walkMinutes: 6,
    },
    {
      id: "a-13",
      amenityType: "park",
      name: "Kallang Riverside Park",
      distanceMeters: 180,
      walkMinutes: 2,
    },
    {
      id: "a-14",
      amenityType: "park",
      name: "Gardens by the Bay East",
      distanceMeters: 400,
      walkMinutes: 5,
    },
    {
      id: "a-15",
      amenityType: "mall",
      name: "Parkway Parade",
      distanceMeters: 1200,
      walkMinutes: 15,
    },
    {
      id: "a-16",
      amenityType: "hospital",
      name: "Parkway East Hospital",
      distanceMeters: 1500,
      walkMinutes: 19,
    },
  ],
  "one-marina-gardens": [
    {
      id: "a-17",
      amenityType: "mrt",
      name: "Marina Bay MRT (NS27/CE2)",
      distanceMeters: 350,
      walkMinutes: 4,
    },
    {
      id: "a-18",
      amenityType: "mrt",
      name: "Gardens by the Bay MRT (TE22)",
      distanceMeters: 250,
      walkMinutes: 3,
    },
    {
      id: "a-19",
      amenityType: "park",
      name: "Gardens by the Bay",
      distanceMeters: 100,
      walkMinutes: 1,
    },
    {
      id: "a-20",
      amenityType: "mall",
      name: "Marina Bay Sands Shoppes",
      distanceMeters: 500,
      walkMinutes: 6,
    },
    {
      id: "a-21",
      amenityType: "mall",
      name: "The Shoppes at Marina Bay Financial Centre",
      distanceMeters: 650,
      walkMinutes: 8,
    },
    {
      id: "a-22",
      amenityType: "school",
      name: "Stamford American International School",
      distanceMeters: 800,
      walkMinutes: 10,
    },
    {
      id: "a-23",
      amenityType: "hospital",
      name: "Raffles Hospital",
      distanceMeters: 1200,
      walkMinutes: 15,
    },
    {
      id: "a-24",
      amenityType: "park",
      name: "Marina Barrage",
      distanceMeters: 700,
      walkMinutes: 9,
    },
  ],
  "norwood-grand": [
    {
      id: "a-25",
      amenityType: "mrt",
      name: "Woodlands South MRT (TE2)",
      distanceMeters: 150,
      walkMinutes: 2,
    },
    {
      id: "a-26",
      amenityType: "mall",
      name: "Causeway Point",
      distanceMeters: 900,
      walkMinutes: 11,
    },
    {
      id: "a-27",
      amenityType: "school",
      name: "Riverside Primary School",
      distanceMeters: 400,
      walkMinutes: 5,
    },
    {
      id: "a-28",
      amenityType: "school",
      name: "Woodlands Ring Secondary School",
      distanceMeters: 550,
      walkMinutes: 7,
    },
    {
      id: "a-29",
      amenityType: "park",
      name: "Woodlands Waterfront",
      distanceMeters: 700,
      walkMinutes: 9,
    },
    {
      id: "a-30",
      amenityType: "bus_interchange",
      name: "Woodlands Bus Interchange",
      distanceMeters: 950,
      walkMinutes: 12,
    },
    {
      id: "a-31",
      amenityType: "hospital",
      name: "Woodlands Health Campus",
      distanceMeters: 1800,
      walkMinutes: 22,
    },
  ],
  "the-collective-at-one-sophia": [
    {
      id: "a-32",
      amenityType: "mrt",
      name: "Dhoby Ghaut MRT (NS24/NE6/CC1)",
      distanceMeters: 200,
      walkMinutes: 3,
    },
    {
      id: "a-33",
      amenityType: "mrt",
      name: "Bencoolen MRT (DT21)",
      distanceMeters: 350,
      walkMinutes: 4,
    },
    {
      id: "a-34",
      amenityType: "mall",
      name: "Plaza Singapura",
      distanceMeters: 300,
      walkMinutes: 4,
    },
    {
      id: "a-35",
      amenityType: "mall",
      name: "The Cathay",
      distanceMeters: 250,
      walkMinutes: 3,
    },
    {
      id: "a-36",
      amenityType: "school",
      name: "Anglo–Chinese School (Junior)",
      distanceMeters: 500,
      walkMinutes: 6,
    },
    {
      id: "a-37",
      amenityType: "park",
      name: "Fort Canning Park",
      distanceMeters: 400,
      walkMinutes: 5,
    },
    {
      id: "a-38",
      amenityType: "park",
      name: "Istana Park",
      distanceMeters: 350,
      walkMinutes: 4,
    },
    {
      id: "a-39",
      amenityType: "hospital",
      name: "Mount Elizabeth Hospital",
      distanceMeters: 800,
      walkMinutes: 10,
    },
  ],
  "tampines-greenvista": [
    {
      id: "a-40",
      amenityType: "mrt",
      name: "Tampines MRT (EW2/DT32)",
      distanceMeters: 600,
      walkMinutes: 8,
    },
    {
      id: "a-41",
      amenityType: "mall",
      name: "Our Tampines Hub",
      distanceMeters: 450,
      walkMinutes: 6,
    },
    {
      id: "a-42",
      amenityType: "school",
      name: "Junyuan Primary School",
      distanceMeters: 350,
      walkMinutes: 4,
    },
    {
      id: "a-43",
      amenityType: "park",
      name: "Tampines Central Park",
      distanceMeters: 200,
      walkMinutes: 3,
    },
    {
      id: "a-44",
      amenityType: "hospital",
      name: "Tampines Polyclinic",
      distanceMeters: 700,
      walkMinutes: 9,
    },
  ],
};

// ─── Districts ───────────────────────────────────────────────

export const districts: DistrictInfo[] = [
  {
    number: 1,
    name: "Raffles Place, Marina Bay",
    region: "CCR",
    projectCount: 3,
    avgPsf: 2850,
    medianPrice: 2800000,
  },
  {
    number: 2,
    name: "Tanjong Pagar, Chinatown",
    region: "CCR",
    projectCount: 2,
    avgPsf: 2450,
    medianPrice: 1950000,
  },
  {
    number: 3,
    name: "Alexandra, Tiong Bahru",
    region: "RCR",
    projectCount: 2,
    avgPsf: 2200,
    medianPrice: 1800000,
  },
  {
    number: 4,
    name: "Harbourfront, Telok Blangah",
    region: "RCR",
    projectCount: 1,
    avgPsf: 2100,
    medianPrice: 1750000,
  },
  {
    number: 5,
    name: "Buona Vista, Pasir Panjang",
    region: "RCR",
    projectCount: 3,
    avgPsf: 2050,
    medianPrice: 1680000,
  },
  {
    number: 6,
    name: "City Hall, Clarke Quay",
    region: "CCR",
    projectCount: 1,
    avgPsf: 2650,
    medianPrice: 2400000,
  },
  {
    number: 7,
    name: "Beach Road, Bugis",
    region: "CCR",
    projectCount: 2,
    avgPsf: 2500,
    medianPrice: 2100000,
  },
  {
    number: 8,
    name: "Farrer Park, Little India",
    region: "RCR",
    projectCount: 1,
    avgPsf: 1950,
    medianPrice: 1350000,
  },
  {
    number: 9,
    name: "Orchard, River Valley",
    region: "CCR",
    projectCount: 4,
    avgPsf: 3100,
    medianPrice: 3200000,
  },
  {
    number: 10,
    name: "Tanglin, Holland",
    region: "CCR",
    projectCount: 3,
    avgPsf: 2900,
    medianPrice: 3500000,
  },
  {
    number: 11,
    name: "Newton, Novena",
    region: "CCR",
    projectCount: 3,
    avgPsf: 2650,
    medianPrice: 2300000,
  },
  {
    number: 12,
    name: "Toa Payoh, Balestier",
    region: "RCR",
    projectCount: 2,
    avgPsf: 1850,
    medianPrice: 1450000,
  },
  {
    number: 13,
    name: "Macpherson, Potong Pasir",
    region: "RCR",
    projectCount: 2,
    avgPsf: 1780,
    medianPrice: 1380000,
  },
  {
    number: 14,
    name: "Eunos, Geylang",
    region: "RCR",
    projectCount: 3,
    avgPsf: 1650,
    medianPrice: 1250000,
  },
  {
    number: 15,
    name: "East Coast, Marine Parade",
    region: "RCR",
    projectCount: 4,
    avgPsf: 2380,
    medianPrice: 2100000,
  },
  {
    number: 16,
    name: "Bedok, Upper East Coast",
    region: "OCR",
    projectCount: 2,
    avgPsf: 1450,
    medianPrice: 1150000,
  },
  {
    number: 17,
    name: "Changi, Loyang",
    region: "OCR",
    projectCount: 1,
    avgPsf: 1250,
    medianPrice: 980000,
  },
  {
    number: 18,
    name: "Tampines, Pasir Ris",
    region: "OCR",
    projectCount: 5,
    avgPsf: 1420,
    medianPrice: 1280000,
  },
  {
    number: 19,
    name: "Punggol, Sengkang",
    region: "OCR",
    projectCount: 4,
    avgPsf: 1350,
    medianPrice: 1180000,
  },
  {
    number: 20,
    name: "Ang Mo Kio, Bishan",
    region: "RCR",
    projectCount: 3,
    avgPsf: 1880,
    medianPrice: 1550000,
  },
  {
    number: 21,
    name: "Clementi, Upper Bukit Timah",
    region: "RCR",
    projectCount: 3,
    avgPsf: 1950,
    medianPrice: 1620000,
  },
  {
    number: 22,
    name: "Jurong, Boon Lay",
    region: "OCR",
    projectCount: 3,
    avgPsf: 1280,
    medianPrice: 1050000,
  },
  {
    number: 23,
    name: "Woodlands, Dairy Farm",
    region: "OCR",
    projectCount: 2,
    avgPsf: 1380,
    medianPrice: 1100000,
  },
  {
    number: 24,
    name: "Lim Chu Kang, Tengah",
    region: "OCR",
    projectCount: 1,
    avgPsf: 1200,
    medianPrice: 950000,
  },
  {
    number: 25,
    name: "Kranji, Admiralty",
    region: "OCR",
    projectCount: 2,
    avgPsf: 1300,
    medianPrice: 1020000,
  },
  {
    number: 26,
    name: "Mandai, Upper Thomson",
    region: "OCR",
    projectCount: 1,
    avgPsf: 1550,
    medianPrice: 1300000,
  },
  {
    number: 27,
    name: "Sembawang, Yishun",
    region: "OCR",
    projectCount: 3,
    avgPsf: 1280,
    medianPrice: 1050000,
  },
  {
    number: 28,
    name: "Seletar, Yio Chu Kang",
    region: "OCR",
    projectCount: 2,
    avgPsf: 1350,
    medianPrice: 1120000,
  },
];

// ─── Price Indices ───────────────────────────────────────────

export const priceIndices: PriceIndex[] = [
  { quarter: "2024 Q2", ccr: 180.5, rcr: 192.1, ocr: 205.3, overall: 195.2 },
  { quarter: "2024 Q3", ccr: 182.1, rcr: 194.8, ocr: 207.1, overall: 197.0 },
  { quarter: "2024 Q4", ccr: 183.8, rcr: 196.5, ocr: 208.6, overall: 198.4 },
  { quarter: "2025 Q1", ccr: 185.2, rcr: 198.2, ocr: 209.8, overall: 199.8 },
  { quarter: "2025 Q2", ccr: 186.1, rcr: 199.5, ocr: 210.5, overall: 200.9 },
  { quarter: "2025 Q3", ccr: 187.5, rcr: 201.2, ocr: 211.3, overall: 202.1 },
  { quarter: "2025 Q4", ccr: 188.3, rcr: 202.5, ocr: 211.8, overall: 203.0 },
  { quarter: "2026 Q1", ccr: 189.2, rcr: 203.8, ocr: 212.4, overall: 203.8 },
];

// ─── Helper lookups ──────────────────────────────────────────

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getDeveloperBySlug(slug: string): Developer | undefined {
  return developers.find((d) => d.slug === slug);
}

export function getProjectsByDeveloper(developerSlug: string): Project[] {
  const dev = getDeveloperBySlug(developerSlug);
  if (!dev) return [];
  return projects.filter((p) => p.developerId === dev.id);
}

export function getProjectsByDistrict(districtNumber: number): Project[] {
  return projects.filter((p) => p.districtNumber === districtNumber);
}

export function getDistrictByNumber(num: number): DistrictInfo | undefined {
  return districts.find((d) => d.number === num);
}
