interface AiSummaryProps {
  summary: string | null;
}

export function AiSummary({ summary }: AiSummaryProps) {
  return (
    <section className="border-b-2 border-foreground px-6 py-16 md:px-12">
      <div className="mx-auto max-w-7xl space-y-4">
        <h2 className="uppercase font-bold tracking-wide text-lg">
          AI Investment Analysis
        </h2>

        <div className="border-2 border-foreground bg-secondary p-6 shadow-[4px_4px_0px_0px_var(--foreground)]">
          {summary ? (
            <p className="leading-relaxed">{summary}</p>
          ) : (
            <p className="text-muted-foreground italic">
              Analysis pending — AI agent will research this project soon.
            </p>
          )}
        </div>

        <p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
          Generated by AI · For research purposes only · Not financial advice
        </p>
      </div>
    </section>
  );
}
